### ISSUE TITLE
false argument AV8BNA

### ISSUE THREAD

**Issue by WarLord211** [s-d-a/DCS-ExportScripts#3]
in the AV8BNA.lua
Line 	[179] = "%.f",	--H2O CONTROLL LAMP
it must be

	[177] = "%.f",	--H2O CONTROLL LAMP

**Comment by mcmicha** [comment]
thanks for report

change entry 
` [179] = "%.f", --H2O CONTROLL LAMP`
to
`[177] = "%.f",	--FLOW W LAMP`

add new button IDs 
`[178] = "%.4f",	--Comm 1 Channel Show Button`
`[179] = "%.4f",	--Comm 2 Channel Show Button`
