### ISSUE TITLE
F-14 support?

### ISSUE THREAD

**Issue by synackack** [s-d-a/DCS-ExportScripts#4]
Anything I can do to help with F-14 support?

**Comment by H-J-P** [comment]
I do not even have the animated graphics for the instruments. Right now, the cockpit of the F-16 is more important.

**Comment by synackack** [comment]
This work

**Comment by synackack** [comment]
[F-14B.zip](https://github.com/s-d-a/DCS-ExportScripts/files/5053117/F-14B.zip)

This works with StreamDeck. Major functions.
